### ISSUE TITLE
How to Zoom in and out when mappviewer is running?

### ISSUE THREAD

**Issue by MartikyHe** [uoip/stereo_ptam#4]
When the mappviewer is refreshing, it seems that  it is unable for users to zoom in and out to see clearer of the whole loop. How could this function be implemented?

**Comment by MartikyHe** [comment]
This is the error feedback:
Traceback (most recent call last):
  File "/home/waimun/anaconda3/envs/py36_sptam/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/waimun/anaconda3/envs/py36_sptam/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/waimun/project/BA/ba_mark/py_ba/stereo_ptam/viewer.py", line 246, in view
    gl.glClear(gl.GL_COLOR_BUFFER_BIT | gl.GL_DEPTH_BUFFER_BIT)
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glClear,
        cArguments = (16640,)
)

**Comment by MartikyHe** [comment]
This is the error feedback:
Traceback (most recent call last):
  File "/home/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stereo_ptam/viewer.py", line 246, in view
    gl.glClear(gl.GL_COLOR_BUFFER_BIT | gl.GL_DEPTH_BUFFER_BIT)
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glClear,
        cArguments = (16640,)
)
